// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGzlL_4JtlNKsMnH6OHUMnmvUdXjk7StM',
    appId: '1:213766810265:web:effec2a3ac54079a452608',
    messagingSenderId: '213766810265',
    projectId: 'nomady-ae4b6',
    authDomain: 'nomady-ae4b6.firebaseapp.com',
    storageBucket: 'nomady-ae4b6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsxIueBfw4hGHHdjmUSaqFZ6dQQwq45J0',
    appId: '1:213766810265:android:e00383ecdba9019f452608',
    messagingSenderId: '213766810265',
    projectId: 'nomady-ae4b6',
    storageBucket: 'nomady-ae4b6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAWdDUypbAt0Rezm54d2Q3lE4PQ0ouGTc',
    appId: '1:213766810265:ios:1a2a0d973a24d81f452608',
    messagingSenderId: '213766810265',
    projectId: 'nomady-ae4b6',
    storageBucket: 'nomady-ae4b6.appspot.com',
    iosClientId: '213766810265-g066km05itbdk3mvqlvgn0m990t7kvj0.apps.googleusercontent.com',
    iosBundleId: 'com.example.nomadlyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAWdDUypbAt0Rezm54d2Q3lE4PQ0ouGTc',
    appId: '1:213766810265:ios:1a2a0d973a24d81f452608',
    messagingSenderId: '213766810265',
    projectId: 'nomady-ae4b6',
    storageBucket: 'nomady-ae4b6.appspot.com',
    iosClientId: '213766810265-g066km05itbdk3mvqlvgn0m990t7kvj0.apps.googleusercontent.com',
    iosBundleId: 'com.example.nomadlyApp',
  );
}
